---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  # require_chef_omnibus: <= 13.0

platforms:
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[pip::default]
    attributes:
